# Generated by Django 2.2.4 on 2019-08-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loggeduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggeduser',
            old_name='username',
            new_name='email',
        ),
    ]
