# Generated by Django 2.2.4 on 2019-08-21 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190821_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loggeduser',
            name='name',
            field=models.CharField(default='User', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loggeduser',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
