# Generated by Django 2.2.4 on 2019-08-05 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0002_auto_20190805_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location_info',
        ),
        migrations.AddField(
            model_name='ticket',
            name='location_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
