# Generated by Django 2.2.4 on 2019-08-05 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20190805_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='staff_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Your Name'),
        ),
    ]
