# Generated by Django 2.2.4 on 2019-08-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Status'),
            preserve_default=False,
        ),
    ]
