# Generated by Django 2.2.4 on 2019-08-07 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20190806_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='staff_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
