# Generated by Django 2.2.4 on 2019-08-07 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0008_auto_20190807_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=255)),
                ('skilled_staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
