# Generated by Django 2.2.4 on 2019-08-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='request_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Skill'),
            preserve_default=False,
        ),
    ]
