# Generated by Django 2.2.4 on 2019-08-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notidication',
            new_name='notification',
        ),
    ]
