# Generated by Django 2.2.4 on 2019-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_ticket_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
