# Generated by Django 2.2.4 on 2019-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_ticket_date_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('smtp_server', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
