# Generated by Django 2.2.4 on 2019-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCreds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('smtp_server', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='email',
        ),
        migrations.RemoveField(
            model_name='email',
            name='password',
        ),
        migrations.RemoveField(
            model_name='email',
            name='port',
        ),
        migrations.RemoveField(
            model_name='email',
            name='smtp_server',
        ),
    ]
